services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: link-a-doodle_api_c
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: link-a-doodle_frontend_c
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - api
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules