services:
  api:
    build:
      context: ./api
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - PORT=5000
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api
