ARG NODE_VERSION=22.14.0

FROM node:${NODE_VERSION}-alpine

ENV NODE_ENV development

RUN npm i -g nodemon

WORKDIR /usr/src/app

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

USER node

COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]
